apiVersion: v1
kind: Pod
metadata:
  name: mypod1
spec:
  containers:
  - image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    name: mypod
    volumeMounts:
      - name: volume
        mountPath: /mnt/volume
  volumes:
  - name: volume
    azureDisk:
      kind: Managed
      diskName: devdisk01
      diskURI: /subscriptions/a7ee7b4a-8947-41aa-b828-6cc170624574/resourcegroups/dev/providers/Microsoft.Compute/disks/devdisk01