apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: kammana/nodeapp:v2
        name: nodeapp
        ports:
        - containerPort: 8080
