apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        role: demo1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
