apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo
  labels:
    role: demo1
spec:
  replicas: 2
  selector:
    matchLabels:
      role: demo1
  template:
    metadata:
      labels:
        role: demo1
    spec:
      containers:
      - name: nginx
        image: nginx
