apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 200m
    defaultRequest:
      memory: 256Mi
      cpu: 200m
    max:
      memory: 700Mi
      cpu: 500m
    min:
      memory: 100Mi
      cpu: 100m
    type: Container