kind: Service
apiVersion: v1
metadata:
  name: rolloutsvc
  namespace: dev
spec:
  selector:
    app: rollout
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer
