---
- name: apache2install
  hosts: webservers
  become: true
  remote_user: root
  task:
    - name: isntallapache
      apt:
        name: apache2
        state: latest
    - name: start apache
      service:
        name: apache2
        state: started
    - name: copy content
      copy:
        content: "Hello world!"
        dest: /var/www/html/index.html