name: name
trigger: 
  branches:
    include:
      - master
pool:
  name: poolname
variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet test
    displayName: run unit tests
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: build application
  - script: docker build -t myapp:v1 .
    displayName: build image
  - script: docker push myapp:v1
    displayName: push image
