apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistentvolumeclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      usage: catphotosapp1
  resources:
    requests:
      storage: 4Gi