apiVersion: v1
kind: Service
metadata:
  name: nginxnodeport
  namespace: nodeport
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 31704
    port: 80
    targetPort: 80
  selector:
    role: demo1